---
- name: Install required packages
  loop:
    - clamav-daemon
    - clamav-freshclam
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  tags:
    - clamav

- name: Create service directory
  ansible.builtin.file:
    path: /etc/systemd/system/clamav-daemon.service.d
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
    state: directory
  tags:
    - clamav

- name: Write service override
  notify:
    - Restart clamav
  ansible.builtin.template:
    src: override.j2
    dest: /etc/systemd/system/clamav-daemon.service.d/override.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - clamav

- name: Write clamav config
  notify:
    - Restart clamav
  ansible.builtin.template:
    src: clamav.j2
    dest: /etc/clamav/clamd.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - clamav

- name: Write freshclam config
  notify:
    - Restart freshclam
  ansible.builtin.template:
    src: freshclam.j2
    dest: /etc/clamav/freshclam.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - clamav

- name: Start freshclam service
  ansible.builtin.systemd:
    name: clamav-freshclam
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - clamav

- name: Start clamav service
  ansible.builtin.systemd:
    name: clamav-daemon
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - clamav

- name: Wait for definitions
  when:
    - clamav_wait_for_definitions > 0
  loop:
    - /var/lib/clamav/daily.cvd
    - /var/lib/clamav/main.cvd
  ansible.builtin.wait_for:
    path: "{{ item }}"
    timeout: "{{ clamav_wait_for_definitions }}"
  tags:
    - clamav

...
