# Standards: 1.2
---
- name: Install required packages
  loop:
    - clamav-daemon
    - clamav-freshclam
  package:
    name: "{{ item }}"
    state: present
  tags:
    - clamav

- name: Create service directory
  file:
    path: /etc/systemd/system/clamav-daemon.service.d
    state: directory
  tags:
    - clamav

- name: Write service override
  notify:
    - Restart clamav
  template:
    src: override.j2
    dest: /etc/systemd/system/clamav-daemon.service.d/override.conf
  tags:
    - clamav

- name: Write clamav config
  notify:
    - Restart clamav
  template:
    src: clamav.j2
    dest: /etc/clamav/clamd.conf
  tags:
    - clamav

- name: Write freshclam config
  notify:
    - Restart freshclam
  template:
    src: freshclam.j2
    dest: /etc/clamav/freshclam.conf
  tags:
    - clamav

- name: Start freshclam service
  systemd:
    name: clamav-freshclam
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - clamav

- name: Start clamav service
  systemd:
    name: clamav-daemon
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - clamav

...
