---
- name: Restart clamav
  systemd:
    name: clamav-daemon
    state: restarted
    daemon_reload: True

- name: Restart freshclam
  systemd:
    name: clamav-freshclam
    state: restarted
    daemon_reload: True

...
